# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Analytics(_IBM):
    _type = "analytics"
    _icon_dir = "resources/ibm/analytics"


class ActionableInsights(_Analytics):
    _icon = "actionable-insights.png"


class AnalysisRecommendations(_Analytics):
    _icon = "analysis-recommendations.png"


class Analytics(_Analytics):
    _icon = "analytics.png"


class ApplicationScanner(_Analytics):
    _icon = "application-scanner.png"


class AutomatedMigration(_Analytics):
    _icon = "automated-migration.png"


class BusinessPerformance(_Analytics):
    _icon = "business-performance.png"


class CommerceAnalytics(_Analytics):
    _icon = "commerce-analytics.png"


class DataCrawler(_Analytics):
    _icon = "data-crawler.png"


class DataIntegration(_Analytics):
    _icon = "data-integration.png"


class DeviceAnalytics(_Analytics):
    _icon = "device-analytics.png"


class KnowledgeStudio(_Analytics):
    _icon = "knowledge-studio.png"


class StreamingComputing(_Analytics):
    _icon = "streaming-computing.png"


# Aliases
