# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Application(_IBM):
    _type = "application"
    _icon_dir = "resources/ibm/application"


class Accelerators(_Application):
    _icon = "accelerators.png"


class ActionableInsight(_Application):
    _icon = "actionable-insight.png"


class AppServer(_Application):
    _icon = "app-server.png"


class ApplicationContainerImage(_Application):
    _icon = "application-container-image.png"


class ApplicationLogic(_Application):
    _icon = "application-logic.png"


class Application(_Application):
    _icon = "application.png"


class AutomationTools(_Application):
    _icon = "automation-tools.png"


class CircuitBreaker(_Application):
    _icon = "circuit-breaker.png"


class ContainerizedApps(_Application):
    _icon = "containerized-apps.png"


class CustomerCare(_Application):
    _icon = "customer-care.png"


class DigitalExperience(_Application):
    _icon = "digital-experience.png"


class DiscoveryApplications(_Application):
    _icon = "discovery-applications.png"


class DistributedOrderManagement(_Application):
    _icon = "distributed-order-management.png"


class ECommerceApplications(_Application):
    _icon = "e-commerce-applications.png"


class IngestionApplication(_Application):
    _icon = "ingestion-application.png"


class IotPlatform(_Application):
    _icon = "iot-platform.png"


class ManagedSolution(_Application):
    _icon = "managed-solution.png"


class Marketing(_Application):
    _icon = "marketing.png"


class Merchandising(_Application):
    _icon = "merchandising.png"


class Microservices(_Application):
    _icon = "microservices.png"


class Opensource(_Application):
    _icon = "opensource.png"


class OpinionatedContainerTemplates(_Application):
    _icon = "opinionated-container-templates.png"


class Payment(_Application):
    _icon = "payment.png"


class SaasApplications(_Application):
    _icon = "saas-applications.png"


class ServerlessComputing(_Application):
    _icon = "serverless-computing.png"


class ServiceBroker(_Application):
    _icon = "service-broker.png"


class SupplyChainLogisticsManagement(_Application):
    _icon = "supply-chain-logistics-management.png"


class Visualization(_Application):
    _icon = "visualization.png"


class WarehouseManagement(_Application):
    _icon = "warehouse-management.png"


class Workload(_Application):
    _icon = "workload.png"


# Aliases
