# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Blockchain(_IBM):
    _type = "blockchain"
    _icon_dir = "resources/ibm/blockchain"


class BlockchainAdminOpsServices(_Blockchain):
    _icon = "blockchain-admin-ops-services.png"


class Communication(_Blockchain):
    _icon = "communication.png"


class Consensus(_Blockchain):
    _icon = "consensus.png"


class DataStoreOffChain(_Blockchain):
    _icon = "data-store-off-chain.png"


class DataStore(_Blockchain):
    _icon = "data-store.png"


class EventListener(_Blockchain):
    _icon = "event-listener.png"


class Events(_Blockchain):
    _icon = "events.png"


class IdentityAccessManagement(_Blockchain):
    _icon = "identity-access-management.png"


class Ledger(_Blockchain):
    _icon = "ledger.png"


class Membership(_Blockchain):
    _icon = "membership.png"


class MessageBus(_Blockchain):
    _icon = "message-bus.png"


class Node(_Blockchain):
    _icon = "node.png"


class SmartContract(_Blockchain):
    _icon = "smart-contract.png"


class TransactionManager(_Blockchain):
    _icon = "transaction-manager.png"


class Wallet(_Blockchain):
    _icon = "wallet.png"


# Aliases
