# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Compute(_IBM):
    _type = "compute"
    _icon_dir = "resources/ibm/compute"


class ClassicInfrastructureTag(_Compute):
    _icon = "classic-infrastructure-tag.png"


class ClassicInfrastructure(_Compute):
    _icon = "classic-infrastructure.png"


class CloudServices(_Compute):
    _icon = "cloud-services.png"


class CloudUniverse(_Compute):
    _icon = "cloud-universe.png"


class Datacenter(_Compute):
    _icon = "datacenter.png"


class EnterpriseTag(_Compute):
    _icon = "enterprise-tag.png"


class Enterprise(_Compute):
    _icon = "enterprise.png"


class IBMCloudTag(_Compute):
    _icon = "ibm-cloud-tag.png"


class IBMCloud(_Compute):
    _icon = "ibm-cloud.png"


class ImageService(_Compute):
    _icon = "image-service.png"


class Instance(_Compute):
    _icon = "instance.png"


class Internet(_Compute):
    _icon = "internet.png"


class KeyService(_Compute):
    _icon = "key-service.png"


class LoadBalancerListener(_Compute):
    _icon = "load-balancer-listener.png"


class LoadBalancerPool(_Compute):
    _icon = "load-balancer-pool.png"


class PublicTag(_Compute):
    _icon = "public-tag.png"


class RegionTag(_Compute):
    _icon = "region-tag.png"


class Region(_Compute):
    _icon = "region.png"


class SecurityGroup(_Compute):
    _icon = "security-group.png"


class SubnetTag(_Compute):
    _icon = "subnet-tag.png"


class Subnet(_Compute):
    _icon = "subnet.png"


class VpcTag(_Compute):
    _icon = "vpc-tag.png"


class VpnPolicy(_Compute):
    _icon = "vpn-policy.png"


class ZoneTag(_Compute):
    _icon = "zone-tag.png"


class Zone(_Compute):
    _icon = "zone.png"


# Aliases

DC = Datacenter
