# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Datastore(_IBM):
    _type = "datastore"
    _icon_dir = "resources/ibm/datastore"


class AnswerStorage(_Datastore):
    _icon = "answer-storage.png"


class Caches(_Datastore):
    _icon = "caches.png"


class Channel(_Datastore):
    _icon = "channel.png"


class Collection(_Datastore):
    _icon = "collection.png"


class ContentStorage(_Datastore):
    _icon = "content-storage.png"


class CuratedDataSources(_Datastore):
    _icon = "curated-data-sources.png"


class DataService(_Datastore):
    _icon = "data-service.png"


class DataSources(_Datastore):
    _icon = "data-sources.png"


class DataSync(_Datastore):
    _icon = "data-sync.png"


class Datastore(_Datastore):
    _icon = "datastore.png"


class DeviceIdentityService(_Datastore):
    _icon = "device-identity-service.png"


class DeviceRegistry(_Datastore):
    _icon = "device-registry.png"


class EnterpriseData(_Datastore):
    _icon = "enterprise-data.png"


class ExternalDataSources(_Datastore):
    _icon = "external-data-sources.png"


class FileRepository(_Datastore):
    _icon = "file-repository.png"


class GroundTruth(_Datastore):
    _icon = "ground-truth.png"


class InternalChannel(_Datastore):
    _icon = "internal-channel.png"


class ModelRepository(_Datastore):
    _icon = "model-repository.png"


class PlatformServices(_Datastore):
    _icon = "platform-services.png"


class PublicApis(_Datastore):
    _icon = "public-apis.png"


class PublicDataSources(_Datastore):
    _icon = "public-data-sources.png"


class UserDirectory(_Datastore):
    _icon = "user-directory.png"


# Aliases
