# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Devtools(_IBM):
    _type = "devtools"
    _icon_dir = "resources/ibm/devtools"


class CollaborativeDevelopment(_Devtools):
    _icon = "collaborative-development.png"


class ConfigurationManagement(_Devtools):
    _icon = "configuration-management.png"


class ContainerOrchestration(_Devtools):
    _icon = "container-orchestration.png"


class ContinuousBuild(_Devtools):
    _icon = "continuous-build.png"


class ContinuousBusinessPlanning(_Devtools):
    _icon = "continuous-business-planning.png"


class ContinuousDeployment(_Devtools):
    _icon = "continuous-deployment.png"


class ContinuousFeedback(_Devtools):
    _icon = "continuous-feedback.png"


class ContinuousRelease(_Devtools):
    _icon = "continuous-release.png"


class ContinuousTesting(_Devtools):
    _icon = "continuous-testing.png"


class DependencyManagement(_Devtools):
    _icon = "dependency-management.png"


class DeploymentAutomation(_Devtools):
    _icon = "deployment-automation.png"


class DeploymentOrchestration(_Devtools):
    _icon = "deployment-orchestration.png"


class Devops(_Devtools):
    _icon = "devops.png"


class Provision(_Devtools):
    _icon = "provision.png"


class TransformationAdvisor(_Devtools):
    _icon = "transformation-advisor.png"


class UpgradeRollback(_Devtools):
    _icon = "upgrade-rollback.png"


class WasVmQuickstarter(_Devtools):
    _icon = "was-vm-quickstarter.png"


# Aliases
