# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Infrastructure(_IBM):
    _type = "infrastructure"
    _icon_dir = "resources/ibm/infrastructure"


class ApplicationRuntime(_Infrastructure):
    _icon = "application-runtime.png"


class Backend(_Infrastructure):
    _icon = "backend.png"


class BareMetalServers(_Infrastructure):
    _icon = "bare-metal-servers.png"


class CloudMessaging(_Infrastructure):
    _icon = "cloud-messaging.png"


class CloudPartnerServices(_Infrastructure):
    _icon = "cloud-partner-services.png"


class ComputeNode(_Infrastructure):
    _icon = "compute-node.png"


class ContainerCatalog(_Infrastructure):
    _icon = "container-catalog.png"


class Dashboard(_Infrastructure):
    _icon = "dashboard.png"


class EdgeServices(_Infrastructure):
    _icon = "edge-services.png"


class EventFeed(_Infrastructure):
    _icon = "event-feed.png"


class EventListener(_Infrastructure):
    _icon = "event-listener.png"


class EventStreaming(_Infrastructure):
    _icon = "event-streaming.png"


class ExistingEnterpriseSystems(_Infrastructure):
    _icon = "existing-enterprise-systems.png"


class HighSpeedDataTransfer(_Infrastructure):
    _icon = "high-speed-data-transfer.png"


class InfrastructureManagement(_Infrastructure):
    _icon = "infrastructure-management.png"


class InterserviceCommunication(_Infrastructure):
    _icon = "interservice-communication.png"


class LoadBalancer(_Infrastructure):
    _icon = "load-balancer.png"


class MessageBus(_Infrastructure):
    _icon = "message-bus.png"


class MicroservicesMesh(_Infrastructure):
    _icon = "microservices-mesh.png"


class MobileProviderNetwork(_Infrastructure):
    _icon = "mobile-provider-network.png"


class MonitoringLogging(_Infrastructure):
    _icon = "monitoring-logging.png"


class Monitoring(_Infrastructure):
    _icon = "monitoring.png"


class Network(_Infrastructure):
    _icon = "network.png"


class OperationalServices(_Infrastructure):
    _icon = "operational-services.png"


class PeerServices(_Infrastructure):
    _icon = "peer-services.png"


class PhysicalInfrastructure(_Infrastructure):
    _icon = "physical-infrastructure.png"


class ServiceDiscovery(_Infrastructure):
    _icon = "service-discovery.png"


class Services(_Infrastructure):
    _icon = "services.png"


class TransformationConnectivity(_Infrastructure):
    _icon = "transformation-connectivity.png"


class VirtualInfrastructure(_Infrastructure):
    _icon = "virtual-infrastructure.png"


class VisualizationRuntime(_Infrastructure):
    _icon = "visualization-runtime.png"


class Vpn(_Infrastructure):
    _icon = "vpn.png"


# Aliases
