# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Management(_IBM):
    _type = "management"
    _icon_dir = "resources/ibm/management"


class AlertNotification(_Management):
    _icon = "alert-notification.png"


class ApiManagement(_Management):
    _icon = "api-management.png"


class AppConfig(_Management):
    _icon = "app-config.png"


class AppLifecycle(_Management):
    _icon = "app-lifecycle.png"


class BusinessServices(_Management):
    _icon = "business-services.png"


class CloudManagementServices(_Management):
    _icon = "cloud-management-services.png"


class CommonManagementServices(_Management):
    _icon = "common-management-services.png"


class ConfigurationManagement(_Management):
    _icon = "configuration-management.png"


class ContainerClusterManagement(_Management):
    _icon = "container-cluster-management.png"


class DeviceManagement(_Management):
    _icon = "device-management.png"


class InformationGovernance(_Management):
    _icon = "information-governance.png"


class ManagedContainerPlatform(_Management):
    _icon = "managed-container-platform.png"


class Metering(_Management):
    _icon = "metering.png"


class MobileBackendApplication(_Management):
    _icon = "mobile-backend-application.png"


class MobileDeviceAgent(_Management):
    _icon = "mobile-device-agent.png"


class MonitoringLogging(_Management):
    _icon = "monitoring-logging.png"


class ProcessManagement(_Management):
    _icon = "process-management.png"


class ProviderCloudPortalService(_Management):
    _icon = "provider-cloud-portal-service.png"


class PushNotification(_Management):
    _icon = "push-notification.png"


class SystemsManagement(_Management):
    _icon = "systems-management.png"


# Aliases
