# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Network(_IBM):
    _type = "network"
    _icon_dir = "resources/ibm/network"


class Bridge(_Network):
    _icon = "bridge.png"


class CloudInternetServices(_Network):
    _icon = "cloud-internet-services.png"


class DirectLink(_Network):
    _icon = "direct-link.png"


class FloatingIp(_Network):
    _icon = "floating-ip.png"


class LoadBalancer(_Network):
    _icon = "load-balancer.png"


class PublicGateway(_Network):
    _icon = "public-gateway.png"


class Router(_Network):
    _icon = "router.png"


class VpnConnection(_Network):
    _icon = "vpn-connection.png"


class VpnGateway(_Network):
    _icon = "vpn-gateway.png"


# Aliases
