# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Security(_IBM):
    _type = "security"
    _icon_dir = "resources/ibm/security"


class Firewall(_Security):
    _icon = "firewall.png"


class Gateway(_Security):
    _icon = "gateway.png"


class IBMFileEncryptionService(_Security):
    _icon = "ibm-file-encryption-service.png"


class IdentityAccessManagement(_Security):
    _icon = "identity-access-management.png"


class InfrastructureSecurity(_Security):
    _icon = "infrastructure-security.png"


class KeyManagementService(_Security):
    _icon = "key-management-service.png"


class Operators(_Security):
    _icon = "operators.png"


class ReverseProxy(_Security):
    _icon = "reverse-proxy.png"


class Rules(_Security):
    _icon = "rules.png"


class SecurityMonitoringIntelligence(_Security):
    _icon = "security-monitoring-intelligence.png"


class Security(_Security):
    _icon = "security.png"


# Aliases
