# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Servicemanagement(_IBM):
    _type = "servicemanagement"
    _icon_dir = "resources/ibm/servicemanagement"


class AlertNotification(_Servicemanagement):
    _icon = "alert-notification.png"


class Api(_Servicemanagement):
    _icon = "api.png"


class BacklogChangeRequest(_Servicemanagement):
    _icon = "backlog-change-request.png"


class ChangeManagement(_Servicemanagement):
    _icon = "change-management.png"


class Collaboration(_Servicemanagement):
    _icon = "collaboration.png"


class ConfigurationManagement(_Servicemanagement):
    _icon = "configuration-management.png"


class Dashboard(_Servicemanagement):
    _icon = "dashboard.png"


class EventCorrelation(_Servicemanagement):
    _icon = "event-correlation.png"


class FiveWhyAnalysis(_Servicemanagement):
    _icon = "five-why-analysis.png"


class IncidentManagement(_Servicemanagement):
    _icon = "incident-management.png"


class KnownErrorDatabase(_Servicemanagement):
    _icon = "known-error-database.png"


class LogMonitoring(_Servicemanagement):
    _icon = "log-monitoring.png"


class Monitoring(_Servicemanagement):
    _icon = "monitoring.png"


class Notification(_Servicemanagement):
    _icon = "notification.png"


class Operations(_Servicemanagement):
    _icon = "operations.png"


class Prioritization(_Servicemanagement):
    _icon = "prioritization.png"


class ProblemManagement(_Servicemanagement):
    _icon = "problem-management.png"


class RequestFulfillment(_Servicemanagement):
    _icon = "request-fulfillment.png"


class Runbook(_Servicemanagement):
    _icon = "runbook.png"


class ServiceManagementTooling(_Servicemanagement):
    _icon = "service-management-tooling.png"


class Slack(_Servicemanagement):
    _icon = "slack.png"


class TicketingTrending(_Servicemanagement):
    _icon = "ticketing-trending.png"


# Aliases
