# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Users(_IBM):
    _type = "users"
    _icon_dir = "resources/ibm/users"


class ApplicationUser(_Users):
    _icon = "application-user.png"


class Browser(_Users):
    _icon = "browser.png"


class BusinessArchitect(_Users):
    _icon = "business-architect.png"


class BusinessUser(_Users):
    _icon = "business-user.png"


class CloudDeveloper(_Users):
    _icon = "cloud-developer.png"


class CloudUser(_Users):
    _icon = "cloud-user.png"


class Device(_Users):
    _icon = "device.png"


class ECommerceUser(_Users):
    _icon = "e-commerce-user.png"


class EndUser(_Users):
    _icon = "end-user.png"


class IntegratedDigitalExperiences(_Users):
    _icon = "integrated-digital-experiences.png"


class IotUser(_Users):
    _icon = "iot-user.png"


class MobileUser(_Users):
    _icon = "mobile-user.png"


class OfflineCapabilities(_Users):
    _icon = "offline-capabilities.png"


class PeerCloud(_Users):
    _icon = "peer-cloud.png"


class PhysicalEntity(_Users):
    _icon = "physical-entity.png"


class ServiceProvider(_Users):
    _icon = "service-provider.png"


class User(_Users):
    _icon = "user.png"


# Aliases
